### ISSUE TITLE
sosreport command fails with Ansible 2.9.6

### ISSUE THREAD

**Issue by Ecno92** [robertdebock/ansible-role-sosreport#1]
## Describe the bug
The sos report command fails with Ansible 2.9.6, which is the default version that comes with Ubuntu Focal.
Running with role from current master (b5cd02da68ce7555959f8d25252705d017cf476b)

Issue is not present with a more recent Ansible version (2.11.1)

Based on your [release log](https://github.com/robertdebock/ansible-role-sosreport/releases/tag/2.0.3) I assume you intend to support this Ansible version.

What about just using the command module without arguments and with the "short" name? It is not ideal, but it should work on all versions.

## Playbook

```yaml
---

- name: Provide sos report
  hosts: hosts
  become: true
  gather_facts: true
  vars:
    sosreport_local_location: "{{ playbook_dir }}/sosreports"
    sosreport_remote_location: "{{ ansible_env.HOME }}/sosreports"
  roles:
    - robertdebock.sosreport

```

## Output

Show at least the error, possible related output, maybe just all the output.

```
TASK [robertdebock.sosreport : run sosreport] ******************************************************************************************fatal: [host]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.builtin.command) module: cmd Supported parameters include: _raw_params, _uses_shell, argv, chdir, creates, executable, removes, stdin, stdin_add_newline, strip_empty_ends, warn"}
```

## Environment

- Control node OS: Ubuntu "20.04.2 LTS (Focal Fossa)"
- Control node Ansible version: 2.9.6
- Managed node OS: RHEL 7
